crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('', include('dashboard.urls')),
    path('documentation/', include('documentation.urls')),
    path('sales/', include('sales.urls')),
    path('finance/', include('finance.urls')),
    path('marketing/', include('marketing.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/finance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.account_overview, name="account_overview"),
    path('voucher/<int:voucher_id>/approve/', views.approve_voucher, name='approve_voucher'),
    path('voucher/add/', views.create_voucher, name="create_voucher"),
    path('voucher/edit/<int:voucher_id>/', views.edit_voucher, name="edit_voucher"),
    path('voucher/delete/<int:voucher_id>/', views.delete_voucher, name="delete_voucher"),
    path('ajax/get-accounts/', views.get_accounts_by_type, name='get_accounts_by_type'),

    path('voucher/<int:voucher_id>/bill/', views.invoice_bill_view, name='invoice_bill'),
]

crm/finance/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from sales.models import Voucher

# Create your models here.
class JournalEntry(models.Model):
  voucher = models.ForeignKey(Voucher, on_delete=models.CASCADE, related_name='journal_entries')

  account_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True)
  account_id = models.PositiveIntegerField(null=True)
  account = GenericForeignKey('account_type', 'account_id')

  debit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  credit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  entry_date = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
      return f"{self.account_type.capitalize()} - Dr: {self.debit} Cr: {self.credit}"

crm/finance/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.contenttypes.models import ContentType

from .models import JournalEntry

from sales.models import Voucher, Client

from company.services import get_employees
from sales.services import get_all_clients


class VoucherForm(forms.ModelForm):
    account_type = forms.ChoiceField(choices=[
        ('', 'Select Account Type'),
        ('client', 'Client'),
        ('employee', 'Employee'),
        # Add more here
    ])
    accounts = forms.ModelChoiceField(queryset=Client.objects.none(), required=False)


    class Meta:
        model = Voucher
        fields = ['type', 'category', 'account_type', 'accounts', 'amount', 'payment_method', 'narration',]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['accounts'].queryset = Client.objects.none()

        if self.instance and self.instance.pk:
            model_name = self.instance.account_type.model if self.instance.account_type else None
            self.initial['account_type'] = model_name

            # Set appropriate queryset for 'accounts' field based on model
            if model_name == 'client':
                self.fields['accounts'].queryset = get_all_clients(request)
                self.initial['accounts'] = self.instance.account
            elif model_name == 'employee':
                self.fields['accounts'].queryset = get_employees(request)
                self.initial['accounts'] = self.instance.account
        else:
            account_type = self.data.get('account_type')
            if account_type == 'client':
                self.fields['accounts'].queryset = get_all_clients(request)
            elif account_type == 'employee':
                self.fields['accounts'].queryset = get_employees(request)

    def clean(self):
        cleaned_data = super().clean()
        account_type = cleaned_data.get('account_type')

        # Check for account_type and convert it to ContentType instance
        if account_type:
            try:
                content_type = ContentType.objects.get(model=account_type)
                cleaned_data['account_type'] = content_type
            except ContentType.DoesNotExist:
                raise forms.ValidationError("Invalid account type selected.")
        return cleaned_data

class JournalEntryForm(forms.ModelForm):
    account_type = forms.ChoiceField(choices=[
        ('client', 'Client'),
        ('employee', 'Employee'),
    ])
    account = forms.ChoiceField(choices=[])

    class Meta:
        model = JournalEntry
        fields = ['account_type', 'debit', 'credit']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['account'].choices = [('', '--- Select ---')]

    def clean(self):
        cleaned_data = super().clean()
        debit = cleaned_data.get('debit', 0)
        credit = cleaned_data.get('credit', 0)

        if debit < 0 or credit < 0:
            raise forms.ValidationError("Debit and Credit cannot be negative.")

        # Custom validation to ensure the journal entries balance out
        if debit and credit:
            if debit != credit:
                raise forms.ValidationError("Debit and Credit amounts must balance.")
        return cleaned_data

JournalEntryFormSet = inlineformset_factory(
    Voucher,
    JournalEntry,
    form=JournalEntryForm,
    extra=2,  # number of empty entries
    can_delete=True
)

crm/finance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Sum

from django.core.paginator import Paginator

from company.decorators import access_level_required

from .tasks import send_invoice_bill_to_client

from sales.services import get_all_clients, get_all_vouchers
from company.services import get_employees, get_user_branch

from sales.models import Voucher

from .forms import JournalEntryForm, VoucherForm


# Create your views here.
@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def account_overview(request):
    clients = get_all_clients(request).order_by('name')
    vouchers = get_all_vouchers(request).order_by('-created_at')

    # Voucher Pagination
    paginator = Paginator(vouchers, 5)
    voucher_page_number = request.GET.get('voucher_page')
    voucher_page_obj = paginator.get_page(voucher_page_number)

    # Client Pagination
    client_paginator = Paginator(clients, 5)
    client_page_number = request.GET.get('client_page')
    client_page_obj = client_paginator.get_page(client_page_number)

    total_revenue = vouchers.filter(type='Receipt').aggregate(total=Sum('amount'))['total'] or 0
    total_expenses = vouchers.filter(type='Payment').aggregate(total=Sum('amount'))['total'] or 0
    total_profit = total_revenue - total_expenses

    context = {
        'clients': clients, 
        'voucher_page_obj': voucher_page_obj,
        'client_page_obj': client_page_obj,
        'total_revenue': total_revenue,
        'total_expenses': total_expenses,
        'total_profit': total_profit
    }

    return render(request, 'finance/overview.html', context=context)

def get_accounts_by_type(request):
    account_type = request.GET.get('account_type')
    print(account_type)
    data = []

    if account_type == 'client':
        accounts = get_all_clients(request)
    elif account_type == 'employee':
        accounts = get_employees(request)
    else:
        accounts = []

    data = [{'id': a.id, 'name': a.name} for a in accounts]
    print(data)
    return JsonResponse({'accounts': data})

@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def create_voucher(request):
    if request.method == 'POST':
        form = VoucherForm(request.POST, request=request)
        if form.is_valid():
            with transaction.atomic():
                voucher = form.save(commit=False)
                
                # Assign generic foreign key
                account_type = form.cleaned_data['account_type']
                account_instance = form.cleaned_data['accounts']

                voucher.account_type = account_type  # ContentType object
                voucher.account_id = account_instance.id
                voucher.branch = get_user_branch(request)
                voucher.created_by = request.user
                voucher.save()
            messages.success(request, 'Voucher created successfully')
            return redirect('account_overview')
        else:
            print(form.errors)
    else:
        form = VoucherForm(request=request)
    context = {
        'form': form
    }
    return render(request, 'finance/create_voucher.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def edit_voucher(request, voucher_id):
    branch = get_user_branch(request)
    instance = get_object_or_404(Voucher, id=voucher_id, branch=branch)
    if request.method == 'POST':
        form = VoucherForm(request.POST, request=request, instance=instance)
        if form.is_valid():
            with transaction.atomic():
                voucher = form.save(commit=False)
                
                voucher.account_type = form.cleaned_data['account_type']
                voucher.account_id = form.cleaned_data['accounts'].id if form.cleaned_data['accounts'] else None
                voucher.save()
            messages.success(request, 'Voucher updated successfully')
            return redirect('account_overview')
        else:
            print(form.errors)
    else:
        form = VoucherForm(request=request, instance=instance)
    context = {
        'form': form
    }
    return render(request, 'finance/edit_voucher.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def delete_voucher(request, voucher_id):
    branch = get_user_branch(request)
    voucher = get_object_or_404(Voucher, id=voucher_id, branch=branch)
    
    if request.method == 'POST':
        voucher.delete()
        messages.success(request, "Voucher deleted successfully.")
        return redirect('sales') 
    return redirect('sales')

@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def invoice_bill_view(request, voucher_id):
    branch = get_user_branch(request)
    invoice = Voucher.objects.get(id=voucher_id, branch=branch)
    context = {
        'invoice': invoice
    }
    return render(request, 'sales/bill/invoice_bill.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Accountant'])
def approve_voucher(request, voucher_id):
    branch = get_user_branch(request)
    voucher = get_object_or_404(Voucher, id=voucher_id, branch=branch)

    if voucher.account_type.name == "client":
        with transaction.atomic():
            #update client 
            client = voucher.account
            client.advance_paid += voucher.amount
            client.due_amount -= voucher.amount
            if client.due_amount == 0:
                client.status = "Paid"
            client.save()
            voucher.status = "Paid"
            voucher.save()

            # Send the invoice bill after transaction
            try:
                send_invoice_bill_to_client.delay(client.id, voucher.id)
            except Exception as email_error:
                print(f"Error sending invoice: {email_error}")
                messages.error(request, "Voucher marked as paid, but email could not be sent.")
            messages.success(request, 'Voucher marked as paid successfully')
        return redirect('account_overview')
    else:
        voucher.status = "Paid"
        voucher.save()
        messages.success(request, 'Voucher marked as paid successfully')
        return redirect('account_overview')

crm/templates/finance/create_voucher.html
{% extends 'base/base.html' %}
{% load custom_filters %}

{% block head_title %}
Voucher
{% endblock head_title %}

{% block content %}
<div class="mt-6">
    <h1 class="font-semibold text-2xl mb-5">New Voucher</h1>
    <div class="justify-between border rounded-xl bg-white p-6 pb-10">
        <form method="post" class="flex flex-col w-10/12 mt-3 ml-3 mr-3 gap-2">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:gap-6 w-full">
                {% for field in form %}
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ field.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ field.label }}
                    </label>   
                    {% if field.name == "narration" %} 
                    {{ form.narration|add_class:'block w-full h-28 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% else %}                         
                    {{ field|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% endif %}
                </div>
                {% endfor %}
                {% comment %} <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.amount.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.amount.label }}
                    </label>                             
                    {{ form.amount|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% for error in form.amount.errors %}
                        <div class="text-red-500 text-sm mt-1">{{ error }}</div>
                    {% endfor %}
                </div> {% endcomment %}
            </div>
            
            <input type="submit" value="Submit"
            class="w-10/12 h-16 rounded-md px-7 py-1 bg-[--primary-color] font-normal text-white mt-3 ml-16" />
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('#id_account_type').change(function () {
            var accountType = $(this).val();
            $.ajax({
                url: "{% url 'get_accounts_by_type' %}",  // Make sure the URL is correct
                data: {
                    'account_type': accountType  // Send the selected account_type to the server
                },
                success: function (data) {
                    var options = '<option value="">Select Account</option>';  // Default empty option
                    data.accounts.forEach(function (account) {
                        options += '<option value="' + account.id + '">' + account.name + '</option>';
                    });
                    $('#id_accounts').html(options);  // Populate the accounts field with options
                }
            });
        });
    });
</script>
  
{% endblock content %}

crm/templates/finance/edit_voucher.html
{% extends 'base/base.html' %}
{% load custom_filters %}

{% block head_title %}
Voucher
{% endblock head_title %}

{% block content %}
<div class="mt-6">
    <h1 class="font-semibold text-2xl mb-5">Edit Voucher</h1>
    <div class="justify-between border rounded-xl bg-white p-6 pb-10">
        <form method="post" class="flex flex-col w-10/12 mt-3 ml-3 mr-3 gap-2">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:gap-6 w-full">
                {% for field in form %}
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ field.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ field.label }}
                    </label>   
                    {% if field.name == "narration" %} 
                    {{ form.narration|add_class:'block w-full h-28 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% else %}                         
                    {{ field|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            
            <input type="submit" value="Update"
            class="w-10/12 h-16 rounded-md px-7 py-1 bg-[--primary-color] font-normal text-white mt-3 ml-16" />
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        $('#id_account_type').change(function () {
            var accountType = $(this).val();
            $.ajax({
                url: "{% url 'get_accounts_by_type' %}",  // Make sure the URL is correct
                data: {
                    'account_type': accountType  // Send the selected account_type to the server
                },
                success: function (data) {
                    var options = '<option value="">Select Account</option>';  // Default empty option
                    data.accounts.forEach(function (account) {
                        options += '<option value="' + account.id + '">' + account.name + '</option>';
                    });
                    $('#id_accounts').html(options);  // Populate the accounts field with options
                }
            });
        });
    });
</script>
  
{% endblock content %}