crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('', include('dashboard.urls')),
    path('documentation/', include('documentation.urls')),
    path('sales/', include('sales.urls')),
    path('finance/', include('finance.urls')),
    path('marketing/', include('marketing.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/sales/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.sales_view, name='sales'),
    path('inquiry/add/', views.inquiry_form_view, name='inquiry_form'),
    path('client/<int:client_id>/edit/', views.edit_client, name='edit_client'),
    path('client/<int:client_id>/delete/', views.delete_client, name='delete_client'),

    path('invoice/add/', views.create_invoice, name="create_invoice"),
    path('invoice/edit/<int:voucher_id>/', views.edit_invoice, name="edit_invoice"),
    path('invoice/delete/<int:voucher_id>/', views.delete_invoice, name="delete_invoice"),
    path('ajax/get-due-amount/', views.get_due_amount, name='get_due_amount'),

    path("revenue-per-year/chart-data/", views.revenue_chart_data_by_year, name="revenue_chart_data_by_year"),
]

crm/sales/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from company.models import User, Branch
from company.services import get_user_branch

from django.utils import timezone

# Create your models here.
class StatusChoices(models.TextChoices):
  PENDING = 'Pending', 'Pending'
  IN_PROGRESS = 'In Progress', 'In Progress'
  PAID = 'Paid', 'Paid'

class Client(models.Model):
  branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='clients')
  name = models.CharField(max_length=50)
  address = models.CharField(max_length=255)
  contact_number = models.CharField(max_length=14)
  email_address = models.EmailField()
  nationality = models.CharField(max_length=50)
  father_name = models.CharField(max_length=50)
  mother_name = models.CharField(max_length=50)
  preferred_country = models.CharField(max_length=150)
  visa_type = models.CharField(max_length=50)
  package_amount = models.DecimalField(max_digits=10, decimal_places=2)
  advance_paid = models.DecimalField(max_digits=10, decimal_places=2)
  due_amount = models.DecimalField(max_digits=10, decimal_places=2)
  more_remarks = models.TextField(null=True, blank=True)
  status = models.CharField(choices=StatusChoices, default=StatusChoices.IN_PROGRESS, max_length=15)
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='assigned_client')
  assigned_date = models.DateTimeField(null=True, blank=True)

  @property
  def is_assigned(self):
    if self.assigned_to is not None:
      return True
    return False
  
  @property
  def has_dues(self):
    if self.due_amount > 0:
      return True
    return False


  def __str__(self):
    return f"{self.name}"

class ClientDocument(models.Model):
  client = models.ForeignKey(Client, on_delete=models.CASCADE)
  document_type = models.CharField(max_length=250)
  document = models.ImageField(upload_to='client_documents/')


class VoucherStatusChoices(models.TextChoices):
  PENDING = 'Pending', 'Pending'
  PAID = 'Paid', 'Paid'

class Voucher(models.Model):
  VOUCHER_TYPE_CHOICES = [
      ('Payment', 'Payment'),
      ('Receipt', 'Receipt'),
      ('Journal', 'Journal'),
      ('Other', 'Other'),
  ]

  VOUCHER_CATEGORY_CHOICES = [
      ('Sales', 'Sales'),
      ('Service', 'Service'),
      ('Salary', 'Salary'),
      ('Manual', 'Manual'),
  ]

  VOUCHER_STATUS_CHOICES = [
      ('Pending', 'Pending'),
      ('Paid', 'Paid'),
      ('Rejected', 'Rejected'),
      ('Cancelled', 'Cancelled'),
  ]

  PAYMENT_METHOD_CHOICES = [
      ('Cash', 'Cash'),
      ('Bank', 'Bank'),
      ('Online', 'Online'),
      ('Cheque', 'Cheque'),
  ]
  branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='vouchers')

  invoice_number = models.CharField(max_length=50, null=True, blank=True, unique=True)
  type = models.CharField(max_length=50, choices=VOUCHER_TYPE_CHOICES)
  category = models.CharField(max_length=50, choices=VOUCHER_CATEGORY_CHOICES)

  # generic foreign key fields
  account_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True)
  account_id = models.PositiveIntegerField(null=True)
  account = GenericForeignKey('account_type', 'account_id')

  amount = models.DecimalField(max_digits=10, decimal_places=2)
  narration = models.TextField(null=True, blank=True)
  payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, null=True, blank=True)

  created_at = models.DateTimeField(auto_now_add=True)
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="created_vouchers")
  updated_at = models.DateTimeField(auto_now=True)
  updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="updated_vouchers")

  status = models.CharField(max_length=20, choices=VOUCHER_STATUS_CHOICES, default='Pending')

  def save(self, *args, **kwargs):
    # Generate invoice_number if it doesn't already exist
    if not self.invoice_number:
        self.invoice_number = self.generate_invoice_number()
    super().save(*args, **kwargs)
    
  def generate_invoice_number(self):
    branch = self.branch
    today_str = timezone.now().strftime('%Y%m%d')
    last_voucher = Voucher.objects.filter(created_at__date=timezone.now().date(), branch=branch).order_by('invoice_number').last()
    if last_voucher:
      last_sequence = int(last_voucher.invoice_number[-3:])
      next_sequence = last_sequence + 1
    else:
      next_sequence = 1
    return f"{today_str}{next_sequence:03}"
      
  def __str__(self):
    return f"{self.type.capitalize()} : {self.category} #{self.invoice_number}"

crm/sales/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.db.models.functions import TruncMonth
from django.db import transaction
from django.db.models import Sum
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory

from django.utils import timezone

from company.decorators import access_level_required

from .models import ClientDocument, Client, Voucher

from .forms import ClientForm, ClientDocumentForm,ClientDocumentFormset, AssignClientForm, InvoiceForm

from . import services
from company.services import get_user_branch

# Create your views here.
@login_required
def revenue_chart_data_by_year(request):
    current_year = timezone.now().year
    previous_year = current_year - 1
    all_vouchers = services.get_all_vouchers(request)

    def get_monthly_revenue(year, all_vouchers):
        monthly_totals = [0] * 12
        vouchers = (
            all_vouchers.filter(type='Receipt', created_at__date__year=year)
            .annotate(month=TruncMonth('created_at__date'))
            .values('month')
            .annotate(total=Sum('amount'))
            .order_by('month')
        )
        for entry in vouchers:
            month_index = entry['month'].month - 1
            monthly_totals[month_index] = float(entry['total'])
        return monthly_totals

    this_year_data = get_monthly_revenue(current_year, all_vouchers)
    last_year_data = get_monthly_revenue(previous_year, all_vouchers)

    return JsonResponse({
        "labels": ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "current_year": current_year,
        "previous_year": previous_year,
        "this_year_revenue": this_year_data,
        "last_year_revenue": last_year_data
    })

@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor', 'Sales Representative'])
def sales_view(request):
    branch = get_user_branch(request)

    if request.user.role == 'sales representative':
        clients = services.get_assigned_clients(request)
    else:
        clients = services.get_all_clients(request)
    sales = clients.filter(status="Pending")

    if request.user.role == 'sales representative':
        vouchers = services.get_assigned_client_vouchers(request)
    else:
        vouchers = services.get_all_client_vouchers(request)

    # revenue
    all_vouchers = services.get_all_vouchers(request)
    total_revenue = vouchers.filter(type='Receipt').aggregate(total=Sum('amount'))['total'] or 0

    assign_client_form = AssignClientForm(branch=branch)
    if request.method == 'POST':
        if request.user.role == 'admin' or request.user.role == 'manager':
            assign_client_form = AssignClientForm(request.POST, branch=branch)
            if assign_client_form.is_valid():
                client = assign_client_form.cleaned_data['client']
                sales_representative = assign_client_form.cleaned_data['sales_representative']
                client.assigned_to = sales_representative
                client.assigned_date = timezone.now()
                client.save()
                messages.success(request, f'Client {client.name} assigned to {sales_representative.first_name} {sales_representative.last_name} successfully')
                return redirect('sales')
            else:
                print(assign_client_form.errors)
        else:
            messages.error(request, "You don't have permission to assign clients")

    context = {
        'clients': clients, 
        'assign_client_form': assign_client_form,
        'sales': sales,
        'vouchers': vouchers,
        'total_revenue': total_revenue
    }

    return render(request, 'sales/overview.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor'])
def inquiry_form_view(request):
    document_types = [
        'Passport Size Photograph',
        'Passport Image',
        'Citizenship Image (Front)',
        'Citizenship Image (Back)',
    ]
    client_form = ClientForm()
    
    # Create formset with initial document_type values
    document_formset = ClientDocumentFormset(
        queryset=ClientDocument.objects.none(),
        initial=[{'document_type': dt} for dt in document_types]
    )

    context = {
        'form': client_form,
        'document_formset': document_formset,
    }

    if request.method == 'POST':
        client_form = ClientForm(request.POST)
        document_formset = ClientDocumentFormset(request.POST, request.FILES)
        if client_form.is_valid() and document_formset.is_valid():
            with transaction.atomic():
                client = client_form.save(commit=False)
                client.branch = get_user_branch(request)
                if client.advance_paid > 0:
                    paid_amount = client.advance_paid
                    client.advance_paid = 0
                    client.due_amount = client.package_amount
                    client.status = "Pending"
                    client.created_by = request.user
                    client.save()
                    # Create Voucher
                    account_type = ContentType.objects.get_for_model(Client)
                    account_id = client.id
                    Voucher.objects.create(
                        branch = client.branch,
                        account_type=account_type,
                        account_id=account_id,
                        type = "Receipt",
                        category = "Sales",
                        amount = paid_amount,
                        narration = "Advance paid while inquiry.",
                        created_by = request.user,
                        status = "Pending",
                    )
                else:
                    client.created_by = request.user
                    client.save()
                for form in document_formset:
                    document = form.save(commit=False)
                    document.client = client
                    document.save()
                messages.success(request, 'Client created successfully')
                return redirect('sales')
        else:
            context['form'] = client_form
            context['document_formset'] = document_formset
            return render(request, 'sales/inquiry_form.html', context=context)

    return render(request, 'sales/inquiry_form.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor'])
def edit_client(request, client_id):
    client = services.get_client(request, client_id)
    client_form = ClientForm(instance=client)
    formset_class = inlineformset_factory(
        Client, ClientDocument, form=ClientDocumentForm,
        extra=0, can_delete=True,
    )
    document_formset = formset_class(instance=client)

    if request.method == 'POST':
        client_form = ClientForm(request.POST, instance=client)
        document_formset = formset_class(request.POST, request.FILES, instance=client)
        if client_form.is_valid() and document_formset.is_valid():
            client_form.save()
            document_formset.save()
            messages.success(request, 'Client details updated successfully')
            return redirect('sales')
        else:
            print(client_form.errors)
            print(document_formset.errors)
    context = {
        'form': client_form,
        'document_formset': document_formset,
        'client': client,
    }
    return render(request, 'sales/edit_client.html', context=context)

@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor'])
def delete_client(request, client_id):
    branch = get_user_branch(request)
    client = get_object_or_404(Client, id=client_id, branch=branch)
    
    if request.method == 'POST':
        client.delete()
        messages.success(request, "Client deleted successfully.")
        return redirect('sales') 
    return redirect('sales')

def get_due_amount(request):
    client_id = request.GET.get('client_id')
    branch = services.get_user_branch(request)
    try:
        client = Client.objects.get(id=client_id, branch=branch)
        return JsonResponse({'due_amount': client.due_amount})
    except Client.DoesNotExist:
        return JsonResponse({'error': 'Client not found'}, status=404)

@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor', 'Sales Representative'])
def create_invoice(request):
    branch = services.get_user_branch(request)
    form = InvoiceForm(request=request)
    if request.method == 'POST':
        form = InvoiceForm(request.POST, request=request)
        if form.is_valid():
            with transaction.atomic():
                voucher = form.save(commit=False)
                voucher.branch = branch
                voucher.type = "Receipt"
                voucher.category = "Sales"
                voucher.created_by = request.user
                voucher.save()
            messages.success(request, 'Invoice created successfully')
            return redirect('sales')
        else:
            print(form.errors)
    context = {
        'form': form
    }
    return render(request, 'sales/create_invoice.html', context=context)


@login_required
@access_level_required(['Admin', 'Manager', 'Counsellor', 'Sales Representative'])
def edit_invoice(request, voucher_id):
    branch = services.get_user_branch(request)
    instance = get_object_or_404(Voucher, id=voucher_id, branch=branch)
    
    form = InvoiceForm(request=request, instance=instance)
    if request.method == 'POST':
        form = InvoiceForm(request.POST, request=request, instance=instance)
        if form.is_valid():
            with transaction.atomic():
                voucher = form.save(commit=False)
                voucher.save()

crm/templates/sales/assign_client_form.html
{% load custom_filters %}

<div class="mt-6">
    <h1 class="font-semibold text-2xl mb-5">Assign Leads</h1>
    <div class="justify-between border rounded-xl bg-white p-6 pb-10">
        <form method="post" class="flex flex-col w-10/12 mt-3 ml-3 mr-3 gap-2">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:gap-6 w-full">
                {% for field in assign_client_form %}
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ field.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ field.label }}
                    </label>                             
                    {{ field|add_class:'block w-full h-14 px-4 py-2 pl-8 text-gray-400 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
                {% endfor %}
            <input type="submit" value="Assign Client"
            class="w-full h-16 rounded-md px-7 py-1 bg-[--primary-color] font-normal text-white mt-3" />
        </form>
    </div>
</div>

crm/templates/sales/create_invoice.html
{% extends 'base/base.html' %}
{% load custom_filters %}

{% block head_title %}
Invoice
{% endblock head_title %}

{% block content %}
<div class="mt-6">
    <h1 class="font-semibold text-2xl mb-5">New Invoice</h1>
    <div class="justify-between border rounded-xl bg-white p-6 pb-10">
        <form method="post" class="flex flex-col w-10/12 mt-3 ml-3 mr-3 gap-2">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:gap-6 w-full">
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.client.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.client.label }}
                    </label>                             
                    {{ form.client|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label class="block mb-3 text-xl font-medium ml-3">
                       Remaining Due:
                    </label>      
                    <input id="due-amount" name="due-amount" class="block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50">                     
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.amount.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.amount.label }}
                    </label>                             
                    {{ form.amount|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% for error in form.amount.errors %}
                        <div class="text-red-500 text-sm mt-1">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.payment_method.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.payment_method.label }}
                    </label>                             
                    {{ form.payment_method|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.narration.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.narration.label }}
                    </label>                             
                    {{ form.narration|add_class:'block w-full h-28 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
            </div>
            
            <input type="submit" value="Submit"
            class="w-10/12 h-16 rounded-md px-7 py-1 bg-[--primary-color] font-normal text-white mt-3 ml-16" />
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const clientSelect = document.querySelector('#id_client');
        const dueAmountSpan = document.querySelector('#due-amount');
    
        clientSelect.addEventListener('change', function() {
            const clientId = this.value;
            if (clientId) {
                fetch(`/sales/ajax/get-due-amount/?client_id=${clientId}`)
                    .then(response => response.json())
                    .then(data => {
                        dueAmountSpan.value = data.due_amount ?? '0.00';
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        dueAmountSpan.value = 'Error fetching due amount';
                    });
            } else {
                dueAmountSpan.value = 'N/A';
            }
        });
    });
</script>
{% endblock content %}

crm/templates/sales/edit_invoice.html
{% extends 'base/base.html' %}
{% load custom_filters %}

{% block head_title %}
Invoice
{% endblock head_title %}

{% block content %}
<div class="mt-6">
    <h1 class="font-semibold text-2xl mb-5">Edit Invoice</h1>
    <div class="justify-between border rounded-xl bg-white p-6 pb-10">
        <form method="post" class="flex flex-col w-10/12 mt-3 ml-3 mr-3 gap-2">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:gap-6 w-full">
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.client.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.client.label }}
                    </label>                             
                    {{ form.client|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.amount.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.amount.label }}
                    </label>                             
                    {{ form.amount|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                    {% for error in form.amount.errors %}
                        <div class="text-red-500 text-sm mt-1">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.payment_method.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.payment_method.label }}
                    </label>                             
                    {{ form.payment_method|add_class:'block w-full h-14 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
                <div class="relative z-0 mb-5 w-full">
                    <label for="{{ form.narration.id_for_label }}" class="block mb-3 text-xl font-medium ml-3">
                        {{ form.narration.label }}
                    </label>                             
                    {{ form.narration|add_class:'block w-full h-28 px-4 py-2 pl-8 bg-gray-50 border border-gray-300 rounded-md focus:border-(--primary-color) focus:ring focus:ring-blue-200 focus:ring-opacity-50' }}
                </div>
            </div>
            
            <input type="submit" value="Update"
            class="w-10/12 h-16 rounded-md px-7 py-1 bg-[--primary-color] font-normal text-white mt-3 ml-16" />
        </form>
    </div>
</div>

{% endblock content %}